name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - h5py
  - pillow
  - requests
  - ipython
  - jupyter
  - pytorch
  - torchvision